### ISSUE TITLE
RTC clock gets ahead of time very quickly

### ISSUE THREAD

**Issue by DrUm78** [FunKey-Project/linux#1]
RTC clock gets ahead of time very quickly. Seems like it's due to the fact that the V3s RTC runs at 32,768Hz (external 32,768Hz RTC crystal) instead of 32kHz (internal 24Mhz crystal) according to Michel's investigation.

Expected behavior:
The RTC should stay sync with real time.

Steps to reproduce:
1. Use  gameblabla's clock app
2. Set the time
3. Wait a few hours (should be noticeable before though)
4. Notice that the FK RTC is way ahead of time (almost 2h ahead after a few days)

**Comment by Michel-FK** [comment]
Fixed with commit 48c28f9

**Comment by DrUm78** [comment]
Thanks Michel! Seems now perfectly synced. 👍
I included the fix in my custom OS:
https://github.com/DrUm78/FunKey-OS/releases

**Comment by Michel-FK** [comment]
Yes, basically, this is what happened: the internal RTC clock is @32kHz, derived from the high-speed 24MHz crystal, it is running when the SoC is on. However when turned off, the RTC is clock @32.768kHz by the external low-speed crystal, so when you resume, it seems that the time spent while off is 32768/32000 in the future...

The way to fix this problem is to save the internal RTC clock @32kHz value in an RTC backed-up register when you modify it, then restore this value and adjust the time by this factor when re-reading it, like when you boot.
